src/Services/e-sender/O2NextGen.ESender.Api/Controllers/BoardController.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using O2NextGen.ESender.Api.Helpers;
using O2NextGen.ESender.Api.Mappings;
using O2NextGen.ESender.Business.Services;
using O2NextGen.Sdk.NetCore.Models.e_sender;

namespace O2NextGen.ESender.Api.Controllers
{
    [AllowAnonymous]
    [Route("board")]
    public class BoardController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly IEmailSenderService _emailSenderService;

        public BoardController(IEmailSender emailSender, IEmailSenderService emailSenderService)
        {
            _emailSender = emailSender;
            _emailSenderService = emailSenderService;
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Index()
        {
            var models = await _emailSenderService.GetAllAsync(CancellationToken.None);
            return View(models.ToViewModel());
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Detail(long id)
        {
            var emailRequest = await _emailSenderService.GetByIdAsync(id, CancellationToken.None);
            if (emailRequest == null)
                return NotFound();
            return View(emailRequest.ToViewModel());
        }

        [HttpPost]
        [Route("id")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, EmailRequestViewModel model)
        {
            var certificate = await _emailSenderService.GetByIdAsync(id, CancellationToken.None);
            if (certificate == null)
                return NotFound();
            certificate.From = model.From;
            certificate.To = model.To;
            certificate.Subject = model.Subject;
            certificate.Body = model.Body;

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("")]
        public async Task<IActionResult> CreateReally(EmailRequestViewModel model)
        {
            var emailRequest = await _emailSenderService.AddAsync(model.ToModel(), CancellationToken.None);
            await _emailSender.Send(model.To, model.Subject, model.Body);
            return RedirectToAction("Index");
        }
    }
}

src/Services/e-sender/O2NextGen.ESender.Api/Controllers/EmailSenderController.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using O2NextGen.ESender.Api.Helpers;
using O2NextGen.ESender.Api.Mappings;
using O2NextGen.ESender.Business.Services;
using O2NextGen.ESender.Data.Entities;
using O2NextGen.Sdk.NetCore.Models.e_sender;

namespace O2NextGen.ESender.Api.Controllers
{
    [AllowAnonymous]
    [Route("api/[controller]")]
    public class EmailSenderController : ControllerBase
    {
        #region Fields

        private readonly IEmailSender _emailSender;
        private readonly IEmailSenderService _emailSenderService;
        
        #endregion

        #region Ctors
        public EmailSenderController(IEmailSender emailSender, IEmailSenderService emailSenderService)
        {
            _emailSender = emailSender;
            _emailSenderService = emailSenderService;
        }
        #endregion
        
        #region Methods

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> GetAllAsync()
        {
            var models = await _emailSenderService.GetAllAsync(CancellationToken.None);
            return Ok(models.ToViewModel());
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> GetByIdAsync(long id, CancellationToken ct)
        {
            var certificate = await _emailSenderService.GetByIdAsync(id, ct);
            if (certificate == null)
                return NotFound();
            return Ok(certificate.ToViewModel());
        }

        [HttpPut]
        [Route("{id}")]
        public async Task<IActionResult> UpdateAsync(long id, [FromBody]EmailRequestViewModel model, CancellationToken ct)
        {
            var certificate = await _emailSenderService.UpdateAsync(model.ToModel(), ct);
            return Ok(certificate.ToViewModel());
        }

        [HttpPost]
        [HttpPut]
        [Route("")]
        public async Task<IActionResult> AddAsync([FromBody]EmailRequestViewModel model, CancellationToken ct)
        {
            var emailRequest = await _emailSenderService.AddAsync(model.ToModel(), ct);
            await _emailSender.Send(model.To, model.Subject, model.Body = EmailNotificationTemplateConstants.OuterBody);
            return CreatedAtAction(nameof(GetByIdAsync), new {id = emailRequest.Id}, emailRequest);
        }

        #endregion

        [HttpDelete]
        [Route("{id}")]
        public async Task<IActionResult> RemoveAsync(long id,CancellationToken ct)
        {
            await _emailSenderService.RemoveAsync(id, ct);
            return NoContent();
        }
    }
}

src/Services/e-sender/O2NextGen.ESender.Api/Controllers/NewCode/EmailTemplateController.cs
using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using O2NextGen.ESender.Data.Entities;

namespace O2NextGen.ESender.Api.Controllers.NewCode
{
    [AllowAnonymous]
    [Route("api/[controller]")]
    public class EmailTemplateController: ControllerBase
    {
        [HttpGet]
        public void Tests()
        {
            Assembly asm = Assembly.GetExecutingAssembly();
            string path = System.IO.Path.GetDirectoryName(asm.Location);
            System.IO.File.WriteAllText(path+@"\index.html", EmailNotificationTemplateConstants.OuterBody);
        }
        
    }
    
    // [AllowAnonymous]
    // [Route("api/[controller]")]
    // public class EmailTemplateController: ControllerBase
    // {
    //     
    // }
}

src/Services/e-sender/O2NextGen.ESender.Api/Controllers/VersionController.cs
using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace O2NextGen.ESender.Api.Controllers
{
    [AllowAnonymous]
    public class VersionController : ControllerBase
    {
        #region Fields

        private readonly IHostingEnvironment _environment;
        private readonly ILogger<VersionController> _logger;

        #endregion


        #region Ctors

        public VersionController(IHostingEnvironment environment, ILogger<VersionController> logger)
        {
            _environment = environment;
            _logger = logger;
        }

        #endregion

        [HttpGet("[controller]")]
        public object Index()
        {
            var exVersion = Assembly.GetExecutingAssembly().GetName().Version;
            _logger.LogInformation($"get version - {exVersion}");
            return new
            {
                Environment = _environment.EnvironmentName,
                Version = exVersion.ToString()
            };
        }
    }
}

src/Services/e-sender/O2NextGen.ESender.Api/Views/Board/Create.cshtml
@model O2NextGen.Sdk.NetCore.Models.e_sender.EmailRequestViewModel

<form asp-controller="Board" asp-action="CreateReally" method="post">
    <label asp-for="From">From</label>
    <input asp-for="From" />
    <label asp-for="To">To</label>
    <input asp-for="To" />
    <label asp-for="Subject">Subject</label>
    <input asp-for="Subject" />
    <label asp-for="Body">Body</label>
    <input asp-for="Body" />
    <button type="submit">Save</button>
</form>

src/Services/e-sender/O2NextGen.ESender.Api/Views/Board/Detail.cshtml
@model O2NextGen.Sdk.NetCore.Models.e_sender.EmailRequestViewModel

<form asp-controller="Board" asp-action="Edit" asp-route-id="@Model.Id">
    <label asp-for="From">From</label>
    <input asp-for="From" />
    <label asp-for="To">To</label>
    <input asp-for="To" />
    <label asp-for="Subject">Subject</label>
    <input asp-for="Subject" />
    <label asp-for="Body">Body</label>
    <input asp-for="Body" />
    <button type="submit">Save</button>
</form>

src/Services/e-sender/O2NextGen.ESender.Api/Views/Board/Index.cshtml
@model IEnumerable<O2NextGen.Sdk.NetCore.Models.e_sender.EmailRequestViewModel>
<h1> E-Sender Service</h1>
<h2>Administration board v1.0.0.0</h2>
<style>
    table { border-spacing: 5px;/*use to work like cellspacing */
          width : 200px;
          height: auto;   
         } 
    
        th, td { padding: 5px; } /*use to work like cellpadding */
</style>
<table>
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.To)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var b in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => b.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => b.From)
            </td>
            <td>
                @Html.DisplayFor(modelItem => b.To)
            </td>
            <td>
                @Html.DisplayFor(modelItem => b.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => b.Body)
            </td>
        </tr>
    }
    </tbody>
</table>
@* @foreach (var certificate in Model) *@
@* { *@
@*     <li> *@
@*         @certificate.Id |  @certificate.From |  @certificate.To | @certificate.Subject | @certificate.Body  *@
@*         $1$ | <a asp-controller="Board" asp-action="Detail" asp-route-id="@certificate.Id">Edit</a> #1# *@
@*     </li> *@
@* } *@

@* <a asp-controller="Board" asp-action="Create">Create</a> *@