src/WebApps/PFRCentr.Mvc/src/PFRCentr.App.MvcClient/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PFRCentr.App.MvcClient.Models.Dto;
using PFRCentr.App.MvcClient.Services;

namespace PFRCentr.App.MvcClient.Controllers;

[Authorize]
public class CategoryController : Controller
{
    private readonly ICGenCategoryService _icGenCategoryService;

    public CategoryController(ICGenCategoryService icGenCategoryService)
    {
        _icGenCategoryService = icGenCategoryService;
    }

    public async Task<ViewResult> CategoryIndex()
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _icGenCategoryService.GetCategoriesAsync<List<CategoryDto>>(token);
        List<ResponseDto> list = null;
        // if (response != null && response.IsSuccess)
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        return View(response);
    }

    public IActionResult CreateCategory()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateCategory(CategoryDto model)
    {
        if (ModelState.IsValid)
        {
            var token = await HttpContext.GetTokenAsync("access_token");
            var response = await _icGenCategoryService.CreateCategoryAsync<CategoryDto>(model, token);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CategoryIndex));
        }

        return View(model);
    }

    public async Task<IActionResult> EditCategory(long categoryId)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _icGenCategoryService.GetCategoryByIdAsync<CategoryDto>(categoryId, token);
        List<ResponseDto> list = null;
        if (response != null)
            return View(response);
        return NotFound();
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        // if (response == null)
        //     return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCategory(CategoryDto model)
    {
        if (ModelState.IsValid)
        {
            var token = await HttpContext.GetTokenAsync("access_token");
            var response = await _icGenCategoryService.UpdateCategoryAsync<CategoryDto>(model.Id, model, token);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CategoryIndex));
        }

        return View(model);
    }

    public async Task<IActionResult> DeleteCategory(long categoryId)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _icGenCategoryService.GetCategoryByIdAsync<CategoryDto>(categoryId, token);
        List<ResponseDto> list = null;
        if (response != null)
            return View(response);
        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCategory(CategoryDto model)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        await _icGenCategoryService.DeleteCategoryAsync<CategoryDto>(model.Id, token);
        return RedirectToAction(nameof(CategoryIndex));
    }
}

src/WebApps/PFRCentr.Mvc/src/PFRCentr.App.MvcClient/Controllers/CertificateController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PFRCentr.App.MvcClient.Models.Dto;
using PFRCentr.App.MvcClient.Services;

namespace PFRCentr.App.MvcClient.Controllers;

[Authorize]
public class CertificateController : Controller
{
    private readonly ICGenCertificateService _cGenCertificateService;

    public CertificateController(ICGenCertificateService cGenCertificateService)
    {
        _cGenCertificateService = cGenCertificateService;
    }

    public async Task<ViewResult> CertificateIndex()
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _cGenCertificateService.GetCertificatesAsync<List<CertificateDto>>(token);
        List<ResponseDto> list = null;
        // if (response != null && response.IsSuccess)
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        return View(response);
    }

    public IActionResult CreateCertificate()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateCertificate(CertificateDto model)
    {
        if (ModelState.IsValid)
        {
            var token = await HttpContext.GetTokenAsync("access_token");
            var response = await _cGenCertificateService.CreateCertificateAsync<CertificateDto>(model, token);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CertificateIndex));
        }

        return View(model);
    }

    public async Task<IActionResult> EditCertificate(long CertificateId)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _cGenCertificateService.GetCertificateByIdAsync<CertificateDto>(CertificateId, token);
        List<ResponseDto> list = null;
        if (response != null)
            return View(response);
        return NotFound();
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        // if (response == null)
        //     return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCertificate(CertificateDto model)
    {
        if (ModelState.IsValid)
        {
            var token = await HttpContext.GetTokenAsync("access_token");
            var response = await _cGenCertificateService.UpdateCertificateAsync<CertificateDto>(model.Id, model,token);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CertificateIndex));
        }

        return View(model);
    }

    public async Task<IActionResult> DeleteCertificate(long CertificateId)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        var response = await _cGenCertificateService.GetCertificateByIdAsync<CertificateDto>(CertificateId, token);
        List<ResponseDto> list = null;
        if (response != null)
            return View(response);
        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCertificate(CertificateDto model)
    {
        var token = await HttpContext.GetTokenAsync("access_token");
        await _cGenCertificateService.DeleteCertificateAsync<CertificateDto>(model.Id, token);
        return RedirectToAction(nameof(CertificateIndex));
    }
}

src/WebApps/PFRCentr.Mvc/src/PFRCentr.App.MvcClient/Controllers/PublishBaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PFRCentr.App.MvcClient.Models.Dto;
using PFRCentr.App.MvcClient.Services;

namespace PFRCentr.App.MvcClient.Controllers;
public class PaginationInfo
{
    public int TotalItems { get; set; }
    public int ItemsPerPage { get; set; }
    public int ActualPage { get; set; }
    public int TotalPages { get; set; }
    public string Previous { get; set; }
    public string Next { get; set; }
}
public class CatalogIndexViewModel
{
    public IEnumerable<PublishCertificateDto> CatalogItems { get; set; }
    public IEnumerable<SelectListItem> Types { get; set; }
    
    public int? BrandFilterApplied { get; set; }
    public int? TypesFilterApplied { get; set; }
    public PaginationInfo PaginationInfo { get; set; }
}

public class PublishBaseController: Controller
{
    private readonly IPublishBase _publishBase;

    public PublishBaseController(IPublishBase publishBase)
    {
        _publishBase = publishBase;
    }
    public async Task<IActionResult> Index(int? TypesFilterApplied, int? page)
    {
        int itemsPage=10 ;
        var catalog = await _publishBase.GetItems<Catalog>(page ?? 0, itemsPage, TypesFilterApplied);
        var vm = new CatalogIndexViewModel()
        {
            CatalogItems = catalog.Data,
            //Types = await _publishBase.GetTypes(),
            TypesFilterApplied = TypesFilterApplied ?? 0,
            PaginationInfo = new PaginationInfo()
            {
                ActualPage = page ?? 0,
                ItemsPerPage = itemsPage , 
                TotalItems = catalog.Count,
                TotalPages = (int)Math.Ceiling(((decimal)catalog.Count / itemsPage))
            }
        };

        vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
        vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

        return View(vm);
    }
}

src/WebApps/PFRCentr.Mvc/src/PFRCentr.App.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PFR Community</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PFRCentr.App.MvcClient.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" /> *@
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PFR Community</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secure">Secure</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pacient Cards</a>
                    </li>
                    <li class="nav-item">
                                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Web site</a>
                                                            </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="PublishBase" asp-action="Index">PublishBase</a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Certificate" asp-action="CertificateIndex">Certificaties</a> *@
                    @* </li> *@
                    
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Admin Panel
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            @* <li> *@
                            @*     <a class="dropdown-item" asp-controller="Home" asp-action="Index">All</a> *@
                            @* </li> *@
                            <li>
                                <a class="dropdown-item" asp-controller="Category" asp-action="CategoryIndex">Categories</a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-controller="Certificate" asp-action="CertificateIndex">Certificates</a>

                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div id="content">
        Denis Prokhorchik
    </div>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.11.0/umd/react.development.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.11.0/umd/react-dom.development.js"></script>
    <script src="js/app.jsx"></script>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - O2Bionics LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/js/all.js" integrity="sha512-MhphDdrtVgCiTUdFBDrRGigpyWU4xU+V/3NzED9A6ZDD879EvIA39i4buHXc8/+iAS+EXh+GBrkduQprR8+qAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/WebApps/PFRCentr.Mvc/src/PFRCentr.App.MvcClient/Views/Shared/_Pagination.cshtml
@model PFRCentr.App.MvcClient.Controllers.PaginationInfo

<div class="esh-pager">
    <div class="container">
        <article class="esh-pager-wrapper row">
            <nav>
                <a class="esh-pager-item esh-pager-item--navigable @Model.Previous"
                   id="Previous"
                   asp-controller="PublishBase"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage -1)"
                   aria-label="Previous">
                    Previous
                </a>

                <span class="esh-pager-item">
                    Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
                </span>

                <a class="esh-pager-item esh-pager-item--navigable @Model.Next"
                   id="Next"
                   asp-controller="PublishBase"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage + 1)"
                   aria-label="Next">
                    Next
                </a>
            </nav>
        </article>
    </div>
</div>