src/WebApps/IdPortal.Mvc/src/IdPortal.App.MvcClient/Controllers/CertificateController.cs
using IdPortal.App.MvcClient.Models.Dto;
using IdPortal.App.MvcClient.Services;
using Microsoft.AspNetCore.Mvc;

namespace IdPortal.App.MvcClient.Controllers;

public class CertificateController : Controller
{
    private readonly ICGenCertificateService _cGenCertificateService;

    public CertificateController(ICGenCertificateService cGenCertificateService)
    {
        _cGenCertificateService = cGenCertificateService;
    }
    public async Task<ViewResult> CertificateIndex()
    {
        var response = await _cGenCertificateService.GetCertificatesAsync<List<CertificateDto>>();
        List<ResponseDto> list = null;
        // if (response != null && response.IsSuccess)
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        return View(response);
    }

    public IActionResult CreateCertificate()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateCertificate(CertificateDto model)
    {
        if (ModelState.IsValid)
        {
            var response = await _cGenCertificateService.CreateCertificateAsync<CertificateDto>(model);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CertificateIndex));
        }
        return View(model);
    }
    
    public async Task<IActionResult> EditCertificate(long CertificateId)
    {
        var response = await _cGenCertificateService.GetCertificateByIdAsync<CertificateDto>(CertificateId);
        List<ResponseDto> list = null;
        if (response != null )
            return View(response);
        return NotFound();
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        // if (response == null)
        //     return View(model);

    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCertificate(CertificateDto model)
    {
        if (ModelState.IsValid)
        {
            var response = await _cGenCertificateService.UpdateCertificateAsync<CertificateDto>(model.Id, model);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(CertificateIndex));
        }
        return View(model);
    }
    
    public async Task<IActionResult> DeleteCertificate(long CertificateId)
    {
        var response = await _cGenCertificateService.GetCertificateByIdAsync<CertificateDto>(CertificateId);
        List<ResponseDto> list = null;
        if (response != null )
            return View(response);
        return NotFound();

    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCertificate(CertificateDto model)
    {
        
            await _cGenCertificateService.DeleteCertificateAsync<CertificateDto>(model.Id);
            return RedirectToAction(nameof(CertificateIndex));
            
    }
}

src/WebApps/IdPortal.Mvc/src/IdPortal.App.MvcClient/Controllers/UserController.cs
using IdPortal.App.MvcClient.Models.Dto;
using IdPortal.App.MvcClient.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IdPortal.App.MvcClient.Controllers;

[Authorize]
public class UserController:Controller
{
    private readonly IIdPortalService _idPortalService;

    public UserController(IIdPortalService idPortalService)
    {
        _idPortalService = idPortalService;
    }
    public async Task<ViewResult> UserIndex()
    {
        var response = await _idPortalService.GetCategoriesAsync<List<UserDto>>();
        List<ResponseDto> list = null;
        // if (response != null && response.IsSuccess)
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        return View(response);
    }

    public IActionResult CreateUser()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateUser(UserDto model)
    {
        if (ModelState.IsValid)
        {
            var response = await _idPortalService.CreateCategoryAsync<UserDto>(model);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(UserIndex));
        }
        return View(model);
    }
    
    public async Task<IActionResult> EditUser(string userId)
    {
        var response = await _idPortalService.GetCategoryByIdAsync<UserDto>(userId);
        List<ResponseDto> list = null;
        if (response != null )
            return View(response);
        return NotFound();
        // {
        //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
        // }
        // if (response == null)
        //     return View(model);

    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditUser(UserDto model)
    {
        if (ModelState.IsValid)
        {
            var response = await _idPortalService.UpdateUserAsync<UserDto>(model.Id, model);
            List<ResponseDto> list = null;
            // if (response != null && response.IsSuccess)
            // {
            //     list = JsonConvert.DeserializeObject<List<ResponseDto>>(response.ToString());
            // }
            // if (response == null)
            //     return View(model);
            return RedirectToAction(nameof(UserIndex));
        }
        return View(model);
    }
    
    public async Task<IActionResult> DeleteUser(string userId)
    {
        var response = await _idPortalService.GetCategoryByIdAsync<UserDto>(userId);
        List<ResponseDto> list = null;
        if (response != null )
            return View(response);
        return NotFound();

    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteUser(UserDto model)
    {
        await _idPortalService.DeleteUserAsync<UserDto>(model.Id);
            return RedirectToAction(nameof(UserIndex));
            
    }
}

src/WebApps/IdPortal.Mvc/src/IdPortal.App.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ID Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/IdPortal.App.MvcClient.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" /> *@
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ID Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secure">Secure</a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pacient Cards</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Web site</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CategoryIndex">Categories</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Certificate" asp-action="CertificateIndex">Certificaties</a> *@
                    @* </li> *@

                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Admin Panel
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            @* <li> *@
                            @*     <a class="dropdown-item" asp-controller="Home" asp-action="Index">All</a> *@
                            @* </li> *@
                            <li>
                                <a class="dropdown-item" asp-controller="User" asp-action="UserIndex">User Management</a>
                            </li>
                            @* <li> *@
                            @*     <a class="dropdown-item" asp-controller="Certificate" asp-action="CertificateIndex">Certificates</a> *@
                            @* *@
                            @* </li> *@
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - O2Bionics LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/js/all.js" integrity="sha512-MhphDdrtVgCiTUdFBDrRGigpyWU4xU+V/3NzED9A6ZDD879EvIA39i4buHXc8/+iAS+EXh+GBrkduQprR8+qAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>